# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alexander\Documents\pereiraDomingos.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class FechasPereira(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(906, 425)
        Form.setStyleSheet("background-color: rgb(0, 51, 51)")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(410, 100, 121, 16))
        self.label_4.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.tableWidgetFechasPereira = QtWidgets.QTableWidget(Form)
        self.tableWidgetFechasPereira.setGeometry(QtCore.QRect(20, 130, 851, 211))
        self.tableWidgetFechasPereira.setStyleSheet("font: 9pt \"Segoe Print\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidgetFechasPereira.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidgetFechasPereira.setObjectName("tableWidgetFechasPereira")
        self.tableWidgetFechasPereira.setColumnCount(6)
        self.tableWidgetFechasPereira.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFechasPereira.setItem(5, 5, item)
        self.tableWidgetFechasPereira.horizontalHeader().setDefaultSectionSize(137)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(290, 30, 351, 41))
        self.label_5.setStyleSheet("font: 75 20pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 100, 121, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.btnVer = QtWidgets.QPushButton(Form)
        self.btnVer.setGeometry(QtCore.QRect(370, 360, 181, 41))
        self.btnVer.setStyleSheet("font: 11pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 204, 102);\n"
"")
        self.btnVer.setObjectName("btnVer")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(680, 100, 121, 16))
        self.label_6.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("Form", "BLOQUE B"))
        item = self.tableWidgetFechasPereira.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidgetFechasPereira.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidgetFechasPereira.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidgetFechasPereira.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidgetFechasPereira.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidgetFechasPereira.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidgetFechasPereira.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidgetFechasPereira.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidgetFechasPereira.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidgetFechasPereira.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidgetFechasPereira.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidgetFechasPereira.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tableWidgetFechasPereira.isSortingEnabled()
        self.tableWidgetFechasPereira.setSortingEnabled(False)
        item = self.tableWidgetFechasPereira.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidgetFechasPereira.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tableWidgetFechasPereira.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("Form", "Fechas pereira domingos"))
        self.label_3.setText(_translate("Form", "BLOQUE A"))
        self.btnVer.setText(_translate("Form", "VER"))
        self.label_6.setText(_translate("Form", "BLOQUE C"))

