# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alexander\Documents\registroFechas.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from logica.Persistence import register_Date
from logica.Persistence import delete_Date
from PyQt5.QtWidgets import QMessageBox
from logica.Persistence import updateDatee


class Ui_Form(object):
    message_box: QMessageBox

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1379, 743)
        Form.setStyleSheet("background-color: rgb(128, 195, 161)")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 120, 1211, 571))
        self.groupBox.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "font: 9pt \"Segoe Print\";\n"
                                    "")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_3.setGeometry(QtCore.QRect(120, 390, 851, 161))
        self.tableWidget_3.setStyleSheet("color: rgb(0, 0, 0);\n"
                                         "background-color: rgb(255, 255, 255);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 5, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(136)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 111, 21))
        self.label_6.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 91, 21))
        self.label_7.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 91, 21))
        self.label_8.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 320, 91, 21))
        self.label_9.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(120, 50, 851, 161))
        self.tableWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "background-color: rgb(255, 255, 255);")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(137)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(250, 20, 121, 16))
        self.label.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
                                 "color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(500, 20, 121, 16))
        self.label_2.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(740, 20, 121, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 450, 91, 21))
        self.label_10.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                    "color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 470, 91, 21))
        self.label_11.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                    "color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(990, 130, 191, 301))

        self.groupBox_2.setObjectName("groupBox_2")

        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 171, 51))
        self.pushButton.setStyleSheet("font: 75 10pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 51, 51);\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 210, 171, 51))
        self.pushButton_2.setStyleSheet("font: 75 10pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 51, 51);\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 140, 171, 51))
        self.pushButton_3.setStyleSheet("font: 75 10pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 51, 51);\n"
"\n"
"")

        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(510, 40, 251, 41))
        self.label_4.setStyleSheet("font: 75 20pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(410, 0, 501, 41))
        self.label_5.setStyleSheet("font: 75 20pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(180, 340, 851, 161))
        self.tableWidget_2.setStyleSheet("font: 9pt \"Segoe Print\";\n"
                                         "color: rgb(0, 0, 0);\n"
                                         "background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 5, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(137)

        self.comboBoxMes1 = QtWidgets.QComboBox(Form)
        self.comboBoxMes1.setGeometry(QtCore.QRect(400, 90, 69, 22))
        self.comboBoxMes1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxMes1.setObjectName("comboBoxMes1")
        items1 = ('', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre')
        self.comboBoxMes1.addItems(items1)
        self.comboBoxDia1 = QtWidgets.QComboBox(Form)
        self.comboBoxDia1.setGeometry(QtCore.QRect(540, 90, 69, 22))
        self.comboBoxDia1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxDia1.setObjectName("comboBoxDia1")
        items2 = ('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
                  '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                  '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31')
        self.comboBoxDia1.addItems(items2)

        self.comboBoxMes2 = QtWidgets.QComboBox(Form)
        self.comboBoxMes2.setGeometry(QtCore.QRect(760, 90, 69, 22))
        self.comboBoxMes2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxMes2.setObjectName("comboBoxMes2")
        items3 = ('', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
                  'Noviembre', 'Diciembre')
        self.comboBoxMes2.addItems(items3)

        self.comboBoxDia2 = QtWidgets.QComboBox(Form)
        self.comboBoxDia2.setGeometry(QtCore.QRect(900, 90, 69, 22))
        self.comboBoxDia2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxDia2.setObjectName("comboBoxDia2")
        items4 = ('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
                  '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                  '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31')
        self.comboBoxDia2.addItems(items4)

        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(200, 90, 151, 31))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "font: 9pt \"Segoe Print\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(340, 90, 47, 20))
        self.label_14.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(490, 90, 47, 21))
        self.label_15.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(650, 90, 31, 21))
        self.label_16.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(700, 90, 41, 20))
        self.label_17.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(850, 90, 47, 21))
        self.label_18.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")


        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.registrarFechas)
        self.pushButton_3.clicked.connect(self.eliminarFechas)
        self.pushButton_2.clicked.connect(self.actualizarFechas)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def registrarFechas(self):
        delete_Date()
        self.tabla1(0)
        self.tabla1(1)
        self.tabla1(2)
        self.tabla1(3)
        self.tabla1(4)
        self.tabla1(5)
        self.tabla2(0)
        self.tabla2(1)
        self.tabla2(2)
        self.tabla2(3)
        self.tabla2(4)
        self.tabla2(5)
        self.tabla3(0)
        self.tabla3(1)
        self.tabla3(2)
        self.tabla3(3)
        self.tabla3(4)
        self.tabla3(5)
        dia1 = str(self.comboBoxDia1.currentText())
        dia2 = str(self.comboBoxDia2.currentText())
        mes1 = str(self.comboBoxMes1.currentText())
        mes2 = str(self.comboBoxMes2.currentText())
        fecha1 = mes1 + dia1
        fecha2 = mes2 + dia2
        register_Date(fecha1, "Encuentro tutoriales", 1, "inductorio")
        register_Date(fecha2, "Encuentros tutoriales", 1, "inductorio")
        self.mostrarMensaje("Información", "¡Fechas registradas exitosamente!", "", QMessageBox.Warning, False)
        self.pushButton.setEnabled(False)

    def tabla1(self, column):

        for row in range(self.tableWidget.rowCount()):
            text = self.tableWidget.item(row, column).text()

            if column == 0:
                register_Date(text, "Encuentros tutoriales", 1, "Primeras fechas")
            if column == 2:
                register_Date(text, "Encuentros tutoriales", 2, "Primeras fechas")
            if column == 4:
                register_Date(text, "Encuentros tutoriales", 3, "Primeras fechas")
            if column == 1:
                register_Date(text, "Habilitaciones", 1, "Primeras fechas")
            if column == 3:
                register_Date(text, "Habilitaciones", 2, "Primeras fechas")
            if column == 5:
                register_Date(text, "Habilitaciones", 3, "Primeras fechas")

    def tabla2(self, column):

        for row2 in range(self.tableWidget_2.rowCount()):
            text2 = self.tableWidget_2.item(row2, column).text()
            if column == 0:
                register_Date(text2, "Encuentros tutoriales", 1, "Fechas alternas")
            if column == 2:
                register_Date(text2, "Encuentros tutoriales", 2, "Fechas alternas")
            if column == 4:
                register_Date(text2, "Encuentros tutoriales", 3, "Fechas alternas")
            if column == 1:
                register_Date(text2, "Habilitaciones", 1, "Fechas alternas")
            if column == 3:
                register_Date(text2, "Habilitaciones", 2, "Fechas alternas")
            if column == 5:
                register_Date(text2, "Habilitaciones", 3, "Fechas alternas")

    def tabla3(self, column):
        for row3 in range(self.tableWidget_3.rowCount()):
            text3 = self.tableWidget_3.item(row3, column).text()

            if column == 0:
                 register_Date(text3, "Encuentros tutoriales", 1, "Pereira domingos")
            if column == 2:
                register_Date(text3, "Encuentros tutoriales", 2, "Pereira domingos")
            if column == 4:
                register_Date(text3, "Encuentros tutoriales", 3, "Pereira domingos")
            if column == 1:
                 register_Date(text3, "Habilitaciones", 1, "Pereira domingos")
            if column == 3:
                 register_Date(text3, "Habilitaciones", 2, "Pereira domingos")
            if column == 5:
                 register_Date(text3, "Habilitaciones", 3, "Pereira domingos")

    def eliminarFechas(self):
        delete_Date()
        self.ponerCeros()
        self.mostrarMensaje("Información", "¡Fechas eliminadas!", "", QMessageBox.Warning, False)
        self.pushButton.setEnabled(True)

    def ponerCeros(self):
        self.tabla111()
        self.tabla222()
        self.tabla333()

    def tabla111(self):
        for row in range(self.tableWidget.rowCount()):
           for col in range(self.tableWidget.columnCount()):
               item = self.tableWidget.item(row, col)
               item.setText("0")

    def tabla222(self):
        for row in range(self.tableWidget_2.rowCount()):
           for col in range(self.tableWidget_2.columnCount()):
               item = self.tableWidget_2.item(row, col)
               item.setText("0")

    def tabla333(self):
        for row in range(self.tableWidget_3.rowCount()):
           for col in range(self.tableWidget_3.columnCount()):
               item = self.tableWidget_3.item(row, col)
               item.setText("0")

    def actualizarFechas(self):
        delete_Date()
        self.tabla11(0)
        self.tabla11(1)
        self.tabla11(2)
        self.tabla11(3)
        self.tabla11(4)
        self.tabla11(5)
        self.tabla22(0)
        self.tabla22(1)
        self.tabla22(2)
        self.tabla22(3)
        self.tabla22(4)
        self.tabla22(5)
        self.tabla33(0)
        self.tabla33(1)
        self.tabla33(2)
        self.tabla33(3)
        self.tabla33(4)
        self.tabla33(5)
        dia1 = str(self.comboBoxDia1.currentText())
        dia2 = str(self.comboBoxDia2.currentText())
        mes1 = str(self.comboBoxMes1.currentText())
        mes2 = str(self.comboBoxMes2.currentText())
        fecha1 = mes1 + dia1
        fecha2 = mes2 + dia2
        register_Date(fecha1, "Encuentro tutoriales", 1, "inductorio")
        register_Date(fecha2, "Encuentros tutoriales", 1, "inductorio")
        self.mostrarMensaje("Información", "¡Fechas actualizadas!", "", QMessageBox.Warning, False)

    def tabla11(self, column):
        for row in range(self.tableWidget.rowCount()):
            text = self.tableWidget.item(row, column).text()

            print(column, "colun")
            if column == 0 or column == 2 or column == 4:
                updateDatee(text, "Encuentros tutoriales", "Primeras fechas")
            else:
                updateDatee(text, "Habilitaciones", "Primeras fechas")

    def tabla22(self, column):
        for row2 in range(self.tableWidget_2.rowCount()):
            text2 = self.tableWidget_2.item(row2, column).text()
            if column == 0 or column == 2 or column == 4:
                updateDatee(text2, "Encuentros tutoriales", "Fechas alternas")
            else:
                updateDatee(text2, "Habilitaciones", "Fechas alternas")

    def tabla33(self, column):
        for row3 in range(self.tableWidget_3.rowCount()):
            text3 = self.tableWidget_3.item(row3, column).text()

            if column == 0 or column == 2 or column == 4:
                 updateDatee(text3, "Encuentros tutoriales", "Pereira domingos")
            else:
                 updateDatee(text3, "Habilitaciones", "Pereira domingos")

    def mostrarMensaje(self, titulo: str, texto: str, texto_informativo: str, tipo_mensaje: QMessageBox,
                       estado: bool):

        self.message_box = QMessageBox()
        self.message_box.setWindowTitle(titulo)
        self.message_box.setText(texto)

        if len(texto_informativo) > 0:
            self.message_box.setInformativeText(texto_informativo)

        if estado:
            btn_si = self.message_box.addButton('Si', QMessageBox.ActionRole)
            btn_no = self.message_box.addButton('No', QMessageBox.ActionRole)
            self.message_box.setDefaultButton(btn_si, btn_no)
        else:
            btn_aceptar = self.message_box.addButton('Aceptar', QMessageBox.ActionRole)
            self.message_box.setDefaultButton(btn_aceptar)
        if tipo_mensaje is not None:
            self.message_box.setIcon(tipo_mensaje)
            self.message_box.exec_()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "FECHAS"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("Form", "PRIMERAS"))
        self.label_7.setText(_translate("Form", "FECHAS"))
        self.label_8.setText(_translate("Form", "FECHAS"))
        self.label_9.setText(_translate("Form", "ALTERNAS"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "BLOQUE A"))
        self.label_2.setText(_translate("Form", "BLOQUE B"))
        self.label_3.setText(_translate("Form", "BLOQUE C"))
        self.label_10.setText(_translate("Form", "PEREIRA"))
        self.label_11.setText(_translate("Form", "DOMINGOS"))
        self.groupBox_2.setTitle(_translate("Form", "OPCIONES"))
        self.pushButton.setText(_translate("Form", "REGISTRAR FECHAS"))
        self.pushButton_2.setText(_translate("Form", "ACTUALIZAR FECHAS"))
        self.pushButton_3.setText(_translate("Form", "ELIMINAR FECHAS"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\"  font-size:16pt; color:#000000;\">Registro de fechas</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\"  font-size:16pt; color:#000000;\">Programación encuentros tutoriales</span></p></body></html>"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_2.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#000000\">INTRODUCTORIO:</span></p></body></html>"))
        self.label_14.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Mes:</span></p></body></html>"))
        self.label_15.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Dia:</span></p></body></html>"))
        self.label_16.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Y</span></p></body></html>"))
        self.label_17.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Mes:</span></p></body></html>"))
        self.label_18.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Dia:</span></p></body></html>"))


