# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alexander\Documents\registroFechas.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from logica.Persistence import register_date
from logica.Persistence import delete_date
from PyQt5.QtWidgets import QMessageBox
from logica.Persistence import update_datee
from logica.Persistence import obtener_fecha


class Ui_Form(object):
    message_box: QMessageBox

    def setup_ui(self, form):
        form.setObjectName("Form")
        form.resize(1379, 743)
        form.setStyleSheet("background-color: rgb(128, 195, 161)")
        self.groupbox = QtWidgets.QGroupBox(form)
        self.groupbox.setGeometry(QtCore.QRect(60, 120, 1211, 571))
        self.groupbox.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "font: 9pt \"Segoe Print\";\n"
                                    "")
        self.groupbox.setObjectName("groupBox")
        self.tablewidget_3 = QtWidgets.QTableWidget(self.groupbox)
        self.tablewidget_3.setGeometry(QtCore.QRect(120, 390, 851, 161))
        self.tablewidget_3.setStyleSheet("color: rgb(0, 0, 0);\n"
                                         "background-color: rgb(255, 255, 255);")
        self.tablewidget_3.setObjectName("tableWidget_3")
        self.tablewidget_3.setColumnCount(6)
        self.tablewidget_3.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_3.setItem(5, 5, item)
        self.tablewidget_3.horizontalHeader().setDefaultSectionSize(136)
        self.label_6 = QtWidgets.QLabel(self.groupbox)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 111, 21))
        self.label_6.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupbox)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 91, 21))
        self.label_7.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupbox)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 91, 21))
        self.label_8.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupbox)
        self.label_9.setGeometry(QtCore.QRect(20, 320, 91, 21))
        self.label_9.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.tablewidget = QtWidgets.QTableWidget(self.groupbox)
        self.tablewidget.setGeometry(QtCore.QRect(120, 50, 851, 161))
        self.tablewidget.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "background-color: rgb(255, 255, 255);")
        self.tablewidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tablewidget.setObjectName("tableWidget")
        self.tablewidget.setColumnCount(6)
        self.tablewidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget.setItem(5, 5, item)
        self.tablewidget.horizontalHeader().setDefaultSectionSize(137)
        self.label = QtWidgets.QLabel(self.groupbox)
        self.label.setGeometry(QtCore.QRect(250, 20, 121, 16))
        self.label.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
                                 "color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupbox)
        self.label_2.setGeometry(QtCore.QRect(500, 20, 121, 16))
        self.label_2.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupbox)
        self.label_3.setGeometry(QtCore.QRect(740, 20, 121, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.groupbox)
        self.label_10.setGeometry(QtCore.QRect(20, 450, 91, 21))
        self.label_10.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                    "color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupbox)
        self.label_11.setGeometry(QtCore.QRect(20, 470, 91, 21))
        self.label_11.setStyleSheet("font: 75 11pt \"Segoe Print\";\n"
                                    "color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.groupbox_2 = QtWidgets.QGroupBox(self.groupbox)
        self.groupbox_2.setGeometry(QtCore.QRect(990, 130, 191, 301))

        self.groupbox_2.setObjectName("groupBox_2")

        self.pushbutton = QtWidgets.QPushButton(self.groupbox_2)
        self.pushbutton.setGeometry(QtCore.QRect(10, 70, 171, 51))
        self.pushbutton.setStyleSheet("font: 75 10pt \"Segoe Print\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(0, 51, 51);\n"
                                      "\n"
                                      "")
        self.pushbutton.setObjectName("pushButton")
        self.pushbutton_2 = QtWidgets.QPushButton(self.groupbox_2)
        self.pushbutton_2.setGeometry(QtCore.QRect(10, 210, 171, 51))
        self.pushbutton_2.setStyleSheet("font: 75 10pt \"Segoe Print\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(0, 51, 51);\n"
                                        "\n"
                                        "")
        self.pushbutton_2.setObjectName("pushButton_2")
        self.pushbutton_3 = QtWidgets.QPushButton(self.groupbox_2)
        self.pushbutton_3.setGeometry(QtCore.QRect(10, 140, 171, 51))
        self.pushbutton_3.setStyleSheet("font: 75 10pt \"Segoe Print\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(0, 51, 51);\n"
                                        "\n"
                                        "")

        self.pushbutton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(form)
        self.label_4.setGeometry(QtCore.QRect(510, 40, 251, 41))
        self.label_4.setStyleSheet("font: 75 20pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(form)
        self.label_5.setGeometry(QtCore.QRect(410, 0, 501, 41))
        self.label_5.setStyleSheet("font: 75 20pt \"Segoe Print\";\n"
                                   "color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.tablewidget_2 = QtWidgets.QTableWidget(form)
        self.tablewidget_2.setGeometry(QtCore.QRect(180, 340, 851, 161))
        self.tablewidget_2.setStyleSheet("font: 9pt \"Segoe Print\";\n"
                                         "color: rgb(0, 0, 0);\n"
                                         "background-color: rgb(255, 255, 255);")
        self.tablewidget_2.setObjectName("tableWidget_2")
        self.tablewidget_2.setColumnCount(6)
        self.tablewidget_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_2.setItem(5, 5, item)
        self.tablewidget_2.horizontalHeader().setDefaultSectionSize(137)

        self.comboboxmes1 = QtWidgets.QComboBox(form)
        self.comboboxmes1.setGeometry(QtCore.QRect(400, 90, 69, 22))
        self.comboboxmes1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboboxmes1.setObjectName("comboBoxMes1")
        items1 = ('', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
                  'Noviembre', 'Diciembre')
        self.comboboxmes1.addItems(items1)
        self.comboboxdia1 = QtWidgets.QComboBox(form)
        self.comboboxdia1.setGeometry(QtCore.QRect(540, 90, 69, 22))
        self.comboboxdia1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboboxdia1.setObjectName("comboBoxDia1")
        items2 = ('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
                  '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                  '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31')
        self.comboboxdia1.addItems(items2)

        self.comboboxmes2 = QtWidgets.QComboBox(form)
        self.comboboxmes2.setGeometry(QtCore.QRect(760, 90, 69, 22))
        self.comboboxmes2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboboxmes2.setObjectName("comboBoxMes2")
        items3 = ('', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
                  'Noviembre', 'Diciembre')
        self.comboboxmes2.addItems(items3)

        self.comboboxdia2 = QtWidgets.QComboBox(form)
        self.comboboxdia2.setGeometry(QtCore.QRect(900, 90, 69, 22))
        self.comboboxdia2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboboxdia2.setObjectName("comboBoxDia2")
        items4 = ('', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
                  '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                  '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31')
        self.comboboxdia2.addItems(items4)

        self.label_13 = QtWidgets.QLabel(form)
        self.label_13.setGeometry(QtCore.QRect(200, 90, 151, 31))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "font: 9pt \"Segoe Print\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(form)
        self.label_14.setGeometry(QtCore.QRect(340, 90, 47, 20))
        self.label_14.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(form)
        self.label_15.setGeometry(QtCore.QRect(490, 90, 47, 21))
        self.label_15.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(form)
        self.label_16.setGeometry(QtCore.QRect(650, 90, 31, 21))
        self.label_16.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(form)
        self.label_17.setGeometry(QtCore.QRect(700, 90, 41, 20))
        self.label_17.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(form)
        self.label_18.setGeometry(QtCore.QRect(850, 90, 47, 21))
        self.label_18.setStyleSheet("font: 8pt \"Segoe Print\";\n"
                                    "color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.retranslate_ui(form)
        self.rellenarcuadro1()
        self.rellenarcuadro2()
        self.rellenarcuadro3()
        self.pushbutton.clicked.connect(self.registrar_fechas)
        self.pushbutton_3.clicked.connect(self.eliminar_fechas)
        self.pushbutton_2.clicked.connect(self.actualizar_fechas)
        QtCore.QMetaObject.connectSlotsByName(form)

    def registrar_fechas(self):
        delete_date()
        self.tabla1(0)
        self.tabla1(1)
        self.tabla1(2)
        self.tabla1(3)
        self.tabla1(4)
        self.tabla1(5)
        self.tabla2(0)
        self.tabla2(1)
        self.tabla2(2)
        self.tabla2(3)
        self.tabla2(4)
        self.tabla2(5)
        self.tabla3(0)
        self.tabla3(1)
        self.tabla3(2)
        self.tabla3(3)
        self.tabla3(4)
        self.tabla3(5)
        dia1 = str(self.comboboxdia1.currentText())
        dia2 = str(self.comboboxdia2.currentText())
        mes1 = str(self.comboboxmes1.currentText())
        mes2 = str(self.comboboxmes2.currentText())
        fecha1 = mes1 + dia1
        fecha2 = mes2 + dia2
        register_date(fecha1, "Encuentro tutoriales", 1, "inductorio")
        register_date(fecha2, "Encuentros tutoriales", 1, "inductorio")
        self.mostrar_mensaje("Información", "¡Fechas registradas exitosamente!", "", QMessageBox.Warning, False)
        self.pushbutton.setEnabled(False)

    def rellenarcuadro1(self):
        res = obtener_fecha("Primeras fechas")
        print(res)
        col: int = 0
        rows: int = 0
        for it in res:
            item = self.tablewidget.item(rows, col)
            item.setText(it)
            print("rows", rows, "col ", col)
            if 5 == rows:
                col = col + 1
                rows = -1
            rows = rows + 1

    def rellenarcuadro2(self):
        res = obtener_fecha("Fechas alternas")
        col: int = 0
        rows: int = 0
        for it in res:
            print(it, "fechas ver")
            item = self.tablewidget_2.item(rows, col)
            item.setText(it)
            print("rows", rows, "col ", col)
            if 5 == rows:
                col = col + 1
                rows = -1
            rows = rows + 1

    def rellenarcuadro3(self):
        res = obtener_fecha("Pereira domingos")
        print(res)
        col: int = 0
        rows: int = 0
        for it in res:
            print(it, "fechas ver")
            item = self.tablewidget_3.item(rows, col)
            item.setText(it)
            print("rows", rows, "col ", col)
            if 5 == rows:
                col = col + 1
                rows = -1
            rows = rows + 1

    def tabla1(self, column):

        for row in range(self.tablewidget.rowCount()):
            text = self.tablewidget.item(row, column).text()

            if column == 0:
                register_date(text, "Encuentros tutoriales", 1, "Primeras fechas")
            if column == 2:
                register_date(text, "Encuentros tutoriales", 2, "Primeras fechas")
            if column == 4:
                register_date(text, "Encuentros tutoriales", 3, "Primeras fechas")
            if column == 1:
                register_date(text, "Habilitaciones", 1, "Primeras fechas")
            if column == 3:
                register_date(text, "Habilitaciones", 2, "Primeras fechas")
            if column == 5:
                register_date(text, "Habilitaciones", 3, "Primeras fechas")

    def tabla2(self, column):

        for row2 in range(self.tablewidget_2.rowCount()):
            text2 = self.tablewidget_2.item(row2, column).text()
            if column == 0:
                register_date(text2, "Encuentros tutoriales", 1, "Fechas alternas")
            if column == 2:
                register_date(text2, "Encuentros tutoriales", 2, "Fechas alternas")
            if column == 4:
                register_date(text2, "Encuentros tutoriales", 3, "Fechas alternas")
            if column == 1:
                register_date(text2, "Habilitaciones", 1, "Fechas alternas")
            if column == 3:
                register_date(text2, "Habilitaciones", 2, "Fechas alternas")
            if column == 5:
                register_date(text2, "Habilitaciones", 3, "Fechas alternas")

    def tabla3(self, column):
        for row3 in range(self.tablewidget_3.rowCount()):
            text3 = self.tablewidget_3.item(row3, column).text()

            if column == 0:
                register_date(text3, "Encuentros tutoriales", 1, "Pereira domingos")
            if column == 2:
                register_date(text3, "Encuentros tutoriales", 2, "Pereira domingos")
            if column == 4:
                register_date(text3, "Encuentros tutoriales", 3, "Pereira domingos")
            if column == 1:
                register_date(text3, "Habilitaciones", 1, "Pereira domingos")
            if column == 3:
                register_date(text3, "Habilitaciones", 2, "Pereira domingos")
            if column == 5:
                register_date(text3, "Habilitaciones", 3, "Pereira domingos")

    def eliminar_Fechas(self):
        delete_date()
        self.poner_ceros()
        self.mostrar_mensaje("Información", "¡Fechas eliminadas!", "", QMessageBox.Warning, False)
        self.pushbutton.setEnabled(True)

    def poner_ceros(self):
        self.tabla111()
        self.tabla222()
        self.tabla333()

    def tabla111(self):
        for row in range(self.tablewidget.rowCount()):
            for col in range(self.tablewidget.columnCount()):
                item = self.tablewidget.item(row, col)
                item.setText("0")

    def tabla222(self):
        for row in range(self.tablewidget_2.rowCount()):
            for col in range(self.tablewidget_2.columnCount()):
                item = self.tablewidget_2.item(row, col)
                item.setText("0")

    def tabla333(self):
        for row in range(self.tablewidget_3.rowCount()):
            for col in range(self.tablewidget_3.columnCount()):
                item = self.tablewidget_3.item(row, col)
                item.setText("0")

    def actualizar_Fechas(self):
        delete_date()
        self.tabla11(0)
        self.tabla11(1)
        self.tabla11(2)
        self.tabla11(3)
        self.tabla11(4)
        self.tabla11(5)
        self.tabla22(0)
        self.tabla22(1)
        self.tabla22(2)
        self.tabla22(3)
        self.tabla22(4)
        self.tabla22(5)
        self.tabla33(0)
        self.tabla33(1)
        self.tabla33(2)
        self.tabla33(3)
        self.tabla33(4)
        self.tabla33(5)
        dia1 = str(self.comboboxdia1.currentText())
        dia2 = str(self.comboboxdia2.currentText())
        mes1 = str(self.comboboxmes1.currentText())
        mes2 = str(self.comboboxmes2.currentText())
        fecha1 = mes1 + dia1
        fecha2 = mes2 + dia2
        update_datee(fecha1, "Encuentro tutoriales", 1, "inductorio")
        update_datee(fecha2, "Encuentros tutoriales", 1, "inductorio")
        self.mostrar_mensaje("Información", "¡Fechas actualizadas!", "", QMessageBox.Warning, False)

    def tabla11(self, column):
        for row in range(self.tablewidget.rowCount()):
            text = self.tablewidget.item(row, column).text()

            if column == 0:
                update_datee(text, "Encuentros tutoriales", 1, "Primeras fechas")
            if column == 2:
                update_datee(text, "Encuentros tutoriales", 2, "Primeras fechas")
            if column == 4:
                update_datee(text, "Encuentros tutoriales", 3, "Primeras fechas")
            if column == 1:
                update_datee(text, "Habilitaciones", 1, "Primeras fechas")
            if column == 3:
                update_datee(text, "Habilitaciones", 2, "Primeras fechas")
            if column == 5:
                update_datee(text, "Habilitaciones", 3, "Primeras fechas")

    def tabla22(self, column):
        for row2 in range(self.tablewidget_2.rowCount()):
            text2 = self.tablewidget_2.item(row2, column).text()
            if column == 0:
                update_datee(text2, "Encuentros tutoriales", 1, "Fechas alternas")
            if column == 2:
                update_datee(text2, "Encuentros tutoriales", 2, "Fechas alternas")
            if column == 4:
                update_datee(text2, "Encuentros tutoriales", 3, "Fechas alternas")
            if column == 1:
                update_datee(text2, "Habilitaciones", 1, "Fechas alternas")
            if column == 3:
                update_datee(text2, "Habilitaciones", 2, "Fechas alternas")
            if column == 5:
                update_datee(text2, "Habilitaciones", 3, "Fechas alternas")

    def tabla33(self, column):
        for row3 in range(self.tablewidget_3.rowCount()):
            text3 = self.tablewidget_3.item(row3, column).text()

            if column == 0:
                update_datee(text3, "Encuentros tutoriales", 1, "Pereira domingos")
            if column == 2:
                update_datee(text3, "Encuentros tutoriales", 2, "Pereira domingos")
            if column == 4:
                update_datee(text3, "Encuentros tutoriales", 3, "Pereira domingos")
            if column == 1:
                update_datee(text3, "Habilitaciones", 1, "Pereira domingos")
            if column == 3:
                update_datee(text3, "Habilitaciones", 2, "Pereira domingos")
            if column == 5:
                update_datee(text3, "Habilitaciones", 3, "Pereira domingos")

    def mostrar_mensaje(self, titulo: str, texto: str, texto_informativo: str, tipo_mensaje: QMessageBox,
                       estado: bool):

        self.message_box = QMessageBox()
        self.message_box.setWindowTitle(titulo)
        self.message_box.setText(texto)

        if len(texto_informativo) > 0:
            self.message_box.setInformativeText(texto_informativo)

        if estado:
            btn_si = self.message_box.addButton('Si', QMessageBox.ActionRole)
            btn_no = self.message_box.addButton('No', QMessageBox.ActionRole)
            self.message_box.setDefaultButton(btn_si, btn_no)
        else:
            btn_aceptar = self.message_box.addButton('Aceptar', QMessageBox.ActionRole)
            self.message_box.setDefaultButton(btn_aceptar)
        if tipo_mensaje is not None:
            self.message_box.setIcon(tipo_mensaje)
            self.message_box.exec_()

    def retranslate_ui(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("Form", "Form"))
        self.groupbox.setTitle(_translate("Form", "FECHAS"))
        item = self.tablewidget_3.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tablewidget_3.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tablewidget_3.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tablewidget_3.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tablewidget_3.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tablewidget_3.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tablewidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablewidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablewidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget_3.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tablewidget_3.isSortingEnabled()
        self.tablewidget_3.setSortingEnabled(False)
        item = self.tablewidget_3.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_3.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tablewidget_3.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("Form", "PRIMERAS"))
        self.label_7.setText(_translate("Form", "FECHAS"))
        self.label_8.setText(_translate("Form", "FECHAS"))
        self.label_9.setText(_translate("Form", "ALTERNAS"))
        item = self.tablewidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tablewidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tablewidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tablewidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tablewidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tablewidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tablewidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablewidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablewidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tablewidget.isSortingEnabled()
        self.tablewidget.setSortingEnabled(False)
        item = self.tablewidget.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tablewidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "BLOQUE A"))
        self.label_2.setText(_translate("Form", "BLOQUE B"))
        self.label_3.setText(_translate("Form", "BLOQUE C"))
        self.label_10.setText(_translate("Form", "PEREIRA"))
        self.label_11.setText(_translate("Form", "DOMINGOS"))
        self.groupbox_2.setTitle(_translate("Form", "OPCIONES"))
        self.pushbutton.setText(_translate("Form", "REGISTRAR FECHAS"))
        self.pushbutton_2.setText(_translate("Form", "ACTUALIZAR FECHAS"))
        self.pushbutton_3.setText(_translate("Form", "ELIMINAR FECHAS"))
        self.label_4.setText(_translate("Form",
                                        "<html><head/><body><p align=\"center\"><span style=\"  font-size:16pt; color:#000000;\">Registro de fechas</span></p></body></html>"))
        self.label_5.setText(_translate("Form",
                                        "<html><head/><body><p align=\"center\"><span style=\"  font-size:16pt; color:#000000;\">Programación encuentros tutoriales</span></p></body></html>"))
        item = self.tablewidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tablewidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tablewidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tablewidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tablewidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tablewidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tablewidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablewidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Habilitaciones"))
        item = self.tablewidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Encuentros Tutoriales"))
        item = self.tablewidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Habilitaciones"))
        __sortingEnabled = self.tablewidget_2.isSortingEnabled()
        self.tablewidget_2.setSortingEnabled(False)
        item = self.tablewidget_2.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(0, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(1, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(2, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(3, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(4, 5)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tablewidget_2.item(5, 5)
        item.setText(_translate("Form", "0"))
        self.tablewidget_2.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("Form",
                                         "<html><head/><body><p><span style=\" color:#000000\">INTRODUCTORIO:</span></p></body></html>"))
        self.label_14.setText(
            _translate("Form",
                       "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Mes:</span></p></body></html>"))
        self.label_15.setText(
            _translate("Form",
                       "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Dia:</span></p></body></html>"))
        self.label_16.setText(
            _translate("Form",
                       "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Y</span></p></body></html>"))
        self.label_17.setText(
            _translate("Form",
                       "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Mes:</span></p></body></html>"))
        self.label_18.setText(
            _translate("Form",
                       "<html><head/><body><p><span style=\" font-size:10pt; color:#000000\">Dia:</span></p></body></html>"))
